# Generated by Django 3.2.4 on 2021-07-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_ans', to='esl_app.answer'),
        ),
    ]
