# Generated by Django 2.2.20 on 2021-07-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esl_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='completion',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer_id',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='test_question_id',
            new_name='test_question',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='related_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esl_app.Question'),
        ),
    ]
