# Generated by Django 3.2.4 on 2021-07-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esl_app', '0003_alter_question_correct_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_answers',
            new_name='correct_answer',
        ),
    ]
